# QueryMind baseline. Every number in PROPOSAL.md is regenerated by a target here.
#
#   make setup        create venv and install pinned dependencies
#   make seed         build data/analytics.db (deterministic, seed 598)
#   make verify-data  check the seeded database against the committed md5
#   make demo         run the headline test case offline (no API key)
#   make test         run the test suite
#   make score        regenerate every accuracy and latency figure from traces
#   make report       score + markdown tables for pasting into the write-up
#   make live         re-run the baseline against ASU OpenCode (needs .env)
#   make all          seed + verify-data + test + score

PY      ?= ./venv/bin/python
PIP     ?= ./venv/bin/pip
PYTHON  ?= python3.11
DB      ?= data/analytics.db
DB_MD5  ?= d612d894b6250755906a962edf27e7ab
TRACES  := $(addprefix --trace eval/results/,b0_live_20260906.jsonl \
             b0_strata_20260906.jsonl b1_live_20260906.jsonl b1_strata_20260906.jsonl)

.PHONY: setup seed verify-data demo test score report live extract clean all

setup:
	$(PYTHON) -m venv venv
	$(PIP) install -q --upgrade pip
	$(PIP) install -q -r requirements-dev.txt
	@echo "[OK] environment ready. Next: make seed"

seed:
	$(PY) scripts/seed_db.py

verify-data:
	@test -f $(DB) || (echo "[FAIL] $(DB) missing - run: make seed"; exit 1)
	@ACTUAL=$$(md5 -q $(DB) 2>/dev/null || md5sum $(DB) | cut -d' ' -f1); \
	 if [ "$$ACTUAL" = "$(DB_MD5)" ]; then \
	   echo "[OK] $(DB) matches the committed md5 ($(DB_MD5))"; \
	 else \
	   echo "[FAIL] md5 mismatch: got $$ACTUAL, expected $(DB_MD5)"; exit 1; \
	 fi

demo:
	$(PY) src/baseline.py --input examples/test1.txt --provider mock

test:
	$(PY) -m pytest tests/ -q

score:
	$(PY) src/score.py $(TRACES)

report:
	$(PY) src/score.py --quiet --markdown $(TRACES)

extract:
	$(PY) scripts/extract_trace.py

live:
	$(PY) src/baseline.py --questions --set easy,hard --arm b0 --provider asu \
	  --trace eval/results/b0_rerun.jsonl

clean:
	rm -rf .pytest_cache src/__pycache__ tests/__pycache__ logs/*.log

all: seed verify-data test score
