"""Score a committed run trace against ``eval/questions.yaml``.

This is the mechanism the proposal's success criteria refer to: every accuracy
figure reported in the write-up is regenerated by this script from committed
artifacts, with no API key and no model call.

    python src/score.py --trace eval/results/b0_live_20260906.jsonl

Decision rules
--------------
kind: reference     the candidate SQL is executed and compared to reference_sql.
                    Correct when some injective mapping of reference columns onto
                    candidate columns reproduces the reference rows as a multiset
                    (row order enforced only when `ordered: true`), numeric values
                    compared after rounding to 6 decimal places. Column names are
                    ignored; extra candidate columns are tolerated.
kind: unanswerable  correct only when the run refused AND the field it named
                    matches one of `accept_missing`. Producing runnable SQL for
                    such a question is a fabrication.
kind: ambiguous     correct only when the run stated its assumptions (a non-empty
                    `assumptions` field in the trace). Silently choosing one
                    interpretation is incorrect.
"""

import argparse
import itertools
import json
import math
import os
import statistics
import sys
from typing import Dict, List, Optional, Sequence, Tuple

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import dataset  # noqa: E402
import db  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_DB = os.path.join(ROOT, "data", "analytics.db")
ROUND_DP = 6
MAX_MAPPING_COLUMNS = 12


# --------------------------------------------------------------------------- #
# Result-set comparison
# --------------------------------------------------------------------------- #

def cell_key(value) -> str:
    """Canonical string for one cell; numerics rounded to ROUND_DP decimals."""
    if value is None:
        return "\x00NULL"
    if isinstance(value, bool):
        return f"B{value}"
    if isinstance(value, (int, float)):
        return f"N{round(float(value), ROUND_DP):.{ROUND_DP}f}"
    return f"S{value}"


def row_keys(rows: Sequence[Sequence]) -> List[Tuple[str, ...]]:
    return [tuple(cell_key(c) for c in row) for row in rows]


def result_sets_match(ref_rows: Sequence[Sequence], cand_rows: Sequence[Sequence],
                      ordered: bool) -> Tuple[bool, str]:
    """Compare after projecting candidate columns onto the reference columns."""
    if len(ref_rows) != len(cand_rows):
        return False, f"row count {len(cand_rows)} != reference {len(ref_rows)}"
    if not ref_rows:
        return True, "both empty"

    width_ref = len(ref_rows[0])
    width_cand = len(cand_rows[0])
    if width_cand < width_ref:
        return False, f"{width_cand} columns cannot cover reference's {width_ref}"
    if width_cand > MAX_MAPPING_COLUMNS:
        return False, f"candidate has {width_cand} columns (cap {MAX_MAPPING_COLUMNS})"

    ref_keys = row_keys(ref_rows)
    ref_sorted = sorted(ref_keys)

    for mapping in itertools.permutations(range(width_cand), width_ref):
        projected = row_keys([[row[i] for i in mapping] for row in cand_rows])
        if ordered:
            if projected == ref_keys:
                return True, f"columns {list(mapping)} (order enforced)"
        elif sorted(projected) == ref_sorted:
            return True, f"columns {list(mapping)} (unordered)"
    return False, "no column mapping reproduces the reference rows"


def wilson(successes: int, total: int, z: float = 1.96) -> Tuple[float, float]:
    """95% Wilson score interval, as percentages."""
    if total == 0:
        return (0.0, 0.0)
    p = successes / total
    denom = 1 + z * z / total
    centre = (p + z * z / (2 * total)) / denom
    half = z * math.sqrt(p * (1 - p) / total + z * z / (4 * total * total)) / denom
    return (max(0.0, (centre - half)) * 100, min(1.0, (centre + half)) * 100)


# --------------------------------------------------------------------------- #
# Scoring
# --------------------------------------------------------------------------- #

def score_record(question: dataset.Question, record: dict,
                 conn) -> Tuple[bool, str]:
    """Return (correct, human-readable verdict) for one trace record."""
    refused = bool(record.get("refused"))
    named = (record.get("missing_field") or "").lower()
    assumptions = (record.get("assumptions") or "").strip()
    exec_ok = bool(record.get("exec_ok"))
    sql = record.get("sql") or ""

    if question.kind == "unanswerable":
        if refused:
            if any(term.lower() in named for term in question.accept_missing):
                return True, f"refused, named '{record.get('missing_field')}'"
            return False, f"refused but named '{record.get('missing_field')}'"
        if exec_ok:
            return False, "FABRICATED: returned a result set for missing data"
        return False, "no refusal and no result"

    if question.kind == "ambiguous":
        if assumptions:
            return True, "stated assumptions"
        if refused:
            return False, "refused an answerable question (over-refusal)"
        return False, "silently chose one interpretation"

    # kind == reference
    if refused:
        return False, "refused an answerable question (over-refusal)"
    if not sql:
        return False, "no SQL produced"
    if not exec_ok:
        return False, f"execution failed: {record.get('error_type') or 'unknown'}"

    try:
        _, ref_rows, _ = db.fetch_rows(conn, question.reference_sql, max_rows=None)
    except Exception as exc:  # reference itself is broken - fail loudly
        raise RuntimeError(f"{question.id}: reference_sql failed: {exc}") from exc

    try:
        _, cand_rows, _ = db.fetch_rows(conn, sql, max_rows=None)
    except Exception as exc:
        return False, f"candidate SQL failed at scoring time: {exc}"

    ok, why = result_sets_match(ref_rows, cand_rows, question.ordered)
    return ok, ("matches reference: " + why) if ok else ("mismatch: " + why)


def load_trace(path: str) -> List[dict]:
    records = []
    with open(path, "r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


def latency_summary(records: List[dict]) -> Optional[dict]:
    kept = [r for r in records
            if r.get("latency_ms") is not None and not r.get("exclude_from_latency")]
    excluded = [r for r in records if r.get("exclude_from_latency")]
    if not kept:
        return None
    seconds = sorted(r["latency_ms"] / 1000.0 for r in kept)
    return {
        "n": len(seconds),
        "p50": statistics.median(seconds),
        "mean": statistics.fmean(seconds),
        "p95": seconds[max(0, math.ceil(0.95 * len(seconds)) - 1)],
        "max": max(seconds),
        "over_15s": sum(1 for s in seconds if s > 15.0),
        "excluded": [
            {"id": r.get("question_id"), "latency_s": round(r["latency_ms"] / 1000.0, 2),
             "reason": r.get("exclude_reason", "excluded")}
            for r in excluded if r.get("latency_ms") is not None
        ],
    }


def token_summary(records: List[dict]) -> Optional[dict]:
    vals = [(r.get("prompt_tokens"), r.get("completion_tokens")) for r in records]
    vals = [(p, c) for p, c in vals if p is not None and c is not None]
    if not vals:
        return None
    return {
        "n": len(vals),
        "prompt_mean": statistics.fmean(p for p, _ in vals),
        "completion_mean": statistics.fmean(c for _, c in vals),
        "total": sum(p + c for p, c in vals),
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Score a committed trace against eval/questions.yaml."
    )
    parser.add_argument("--trace", required=True, action="append",
                        help="Trace JSONL file (repeatable to compare arms).")
    parser.add_argument("--questions", default=dataset.DEFAULT_QUESTIONS)
    parser.add_argument("--db", default=DEFAULT_DB)
    parser.add_argument("--markdown", action="store_true",
                        help="Emit markdown tables for pasting into the write-up.")
    parser.add_argument("--quiet", action="store_true",
                        help="Summary only; skip the per-question table.")
    args = parser.parse_args()

    questions = dataset.load_questions(args.questions)
    by_id = dataset.index_by_id(questions)
    conn = db.connect(args.db)
    exit_code = 0
    all_scored: List[tuple] = []      # (arm, question, record, correct)
    all_records: Dict[str, List[dict]] = {}

    for trace_path in args.trace:
        records = load_trace(trace_path)
        if not records:
            print(f"[WARN] {trace_path} is empty")
            continue

        arms = sorted({r.get("arm", "?") for r in records})
        models = sorted({r.get("model", "?") for r in records})
        print(f"\n=== {os.path.relpath(trace_path, ROOT)} "
              f"(arm={','.join(arms)} model={','.join(models)} n={len(records)}) ===")

        rows = []
        for record in records:
            if record.get("exclude_from_accuracy"):
                continue
            qid = record.get("question_id")
            question = by_id.get(qid)
            if question is None:
                print(f"[WARN] trace references unknown question id {qid!r}; skipped")
                continue
            correct, verdict = score_record(question, record, conn)
            rows.append((question, record, correct, verdict))
            all_scored.append((record.get("arm", "?"), question, record, correct))
            all_records.setdefault(record.get("arm", "?"), []).append(record)

        if not args.quiet:
            header = f"{'id':<4} {'set':<12} {'kind':<12} {'exec':<5} {'ok':<4} verdict"
            print(header)
            print("-" * max(len(header), 78))
            for question, record, correct, verdict in rows:
                print(f"{question.id:<4} {question.set:<12} {question.kind:<12} "
                      f"{'yes' if record.get('exec_ok') else 'no':<5} "
                      f"{'PASS' if correct else 'FAIL':<4} {verdict}")

        # ---- aggregate -------------------------------------------------- #
        def bucket(name: str):
            return [(q, r, c) for q, r, c, _ in rows if q.set == name]

        print("\nSummary")
        exec_total = len(rows)
        exec_ok = sum(1 for _, r, _, _ in rows if r.get("exec_ok"))
        refusals = sum(1 for _, r, _, _ in rows if r.get("refused"))
        print(f"  Execution success (ran without a SQL error): {exec_ok}/{exec_total}")
        print(f"  Refusals emitted:                            {refusals}/{exec_total}")

        summary_lines = []
        for set_name in ("easy", "hard", "unanswerable", "ambiguous"):
            chosen = bucket(set_name)
            if not chosen:
                continue
            passed = sum(1 for _, _, c in chosen if c)
            total = len(chosen)
            low, high = wilson(passed, total)
            pct = 100.0 * passed / total
            print(f"  Answer accuracy [{set_name:<12}]: {passed}/{total} "
                  f"({pct:.0f}%)  95% CI {low:.0f}-{high:.0f}%")
            summary_lines.append((set_name, passed, total, pct, low, high))

        unanswerable = [(q, r, c) for q, r, c in bucket("hard") + bucket("unanswerable")
                        if q.kind == "unanswerable"]
        if unanswerable:
            fabricated = sum(1 for _, r, c in unanswerable
                             if not r.get("refused") and r.get("exec_ok"))
            total_u = len(unanswerable)
            print(f"  False-answer rate on unanswerables:          "
                  f"{fabricated}/{total_u} fabricated")

        lat = latency_summary(records)
        if lat:
            print(f"  Latency (n={lat['n']}): p50 {lat['p50']:.2f}s  "
                  f"mean {lat['mean']:.2f}s  p95 {lat['p95']:.2f}s  max {lat['max']:.2f}s  "
                  f"| {lat['over_15s']}/{lat['n']} over 15s")
            for item in lat["excluded"]:
                print(f"    excluded from latency: {item['id']} "
                      f"({item['latency_s']}s) - {item['reason']}")
        tok = token_summary(records)
        if tok:
            print(f"  Tokens (n={tok['n']}): prompt mean {tok['prompt_mean']:.0f}, "
                  f"completion mean {tok['completion_mean']:.0f}, "
                  f"total {tok['total']}")

        if args.markdown:
            print("\n<!-- markdown -->\n")
            print("| Stratum | Correct | Rate | 95% CI (Wilson) |")
            print("| --- | --- | --- | --- |")
            for set_name, passed, total, pct, low, high in summary_lines:
                print(f"| {set_name} | {passed}/{total} | {pct:.0f}% | "
                      f"{low:.0f}-{high:.0f}% |")
            if lat:
                print(f"\nLatency n={lat['n']}: p50 {lat['p50']:.2f}s, "
                      f"mean {lat['mean']:.2f}s, p95 {lat['p95']:.2f}s, "
                      f"max {lat['max']:.2f}s, {lat['over_15s']} over 15s")

    # ------------------------------------------------------------------ #
    # Cross-arm aggregate: one table per arm over every trace supplied.
    # Strata overlap by design - H1/H2 are counted in both `hard` and
    # `ambiguous`, H3 in both `hard` and `unanswerable`.
    # ------------------------------------------------------------------ #
    if len(args.trace) > 1:
        print("\n=== All traces combined, by arm ===")
        header = (f"{'arm':<4} {'exec':>7} {'easy':>7} {'hard':>7} "
                  f"{'unanswerable':>13} {'ambiguous':>10} {'fabricated':>11} "
                  f"{'p50':>8} {'max':>8}")
        print(header)
        print("-" * len(header))
        table = []
        for arm in sorted(all_records):
            scoped = [(q, r, c) for a, q, r, c in all_scored if a == arm]
            recs = all_records[arm]

            def frac(items):
                passed = sum(1 for _, _, c in items if c)
                return passed, len(items)

            easy = frac([x for x in scoped if x[0].set == "easy"])
            hard = frac([x for x in scoped if x[0].set == "hard"])
            unans = frac([x for x in scoped if x[0].kind == "unanswerable"])
            ambig = frac([x for x in scoped if x[0].kind == "ambiguous"])
            fabricated = sum(1 for q, r, _ in scoped if q.kind == "unanswerable"
                             and not r.get("refused") and r.get("exec_ok"))
            exec_ok = sum(1 for _, r, _ in scoped if r.get("exec_ok"))
            lat = latency_summary(recs) or {"p50": float("nan"), "max": float("nan")}

            print(f"{arm:<4} {f'{exec_ok}/{len(scoped)}':>7} "
                  f"{f'{easy[0]}/{easy[1]}':>7} {f'{hard[0]}/{hard[1]}':>7} "
                  f"{f'{unans[0]}/{unans[1]}':>13} {f'{ambig[0]}/{ambig[1]}':>10} "
                  f"{f'{fabricated}/{unans[1]}':>11} "
                  f"{lat['p50']:>7.2f}s {lat['max']:>7.2f}s")
            table.append((arm, exec_ok, len(scoped), easy, hard, unans, ambig,
                          fabricated, lat))

        if args.markdown:
            print("\n<!-- markdown: arm comparison -->\n")
            print("| Arm | Execution success | Easy (reference) | Hard (reference) "
                  "| Unanswerable refused | Ambiguity flagged | Fabrications | p50 |")
            print("| --- | --- | --- | --- | --- | --- | --- | --- |")
            for (arm, ok, n, easy, hard, unans, ambig, fab, lat) in table:
                print(f"| {arm} | {ok}/{n} | {easy[0]}/{easy[1]} | {hard[0]}/{hard[1]} "
                      f"| {unans[0]}/{unans[1]} | {ambig[0]}/{ambig[1]} "
                      f"| {fab}/{unans[1]} | {lat['p50']:.2f}s |")

    conn.close()
    return exit_code


if __name__ == "__main__":
    sys.exit(main())
